EncuestasINEI_PU/EncuestasINEI/Controllers/RespuestasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EncuestasINEI.Models;
using EncuestasINEI.SecurityFilters;

namespace EncuestasINEI.Controllers
{
    [LoggedOnAttribute]
    public class RespuestasController : Controller
    {
        private EncuestasINEIEntitiesContext db = new EncuestasINEIEntitiesContext();

        // GET: Respuestas
        public ActionResult Index()
        {
            var respuesta = db.Respuesta.Include(r => r.Pregunta).Include(r => r.Usuario_Encuesta);
            return View(respuesta.ToList());
        }

        // GET: Respuestas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Respuesta respuesta = db.Respuesta.Find(id);
            if (respuesta == null)
            {
                return HttpNotFound();
            }
            return View(respuesta);
        }

        // GET: Respuestas/Create
        public ActionResult Create()
        {
            ViewBag.PreguntaID = new SelectList(db.Pregunta, "ID", "Descripcion");
            ViewBag.Usuario_EncuestaID = new SelectList(db.Usuario_Encuesta, "ID", "ID");
            return View();
        }

        // POST: Respuestas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Usuario_EncuestaID,PreguntaID,Texto")] Respuesta respuesta)
        {
            if (ModelState.IsValid)
            {
                db.Respuesta.Add(respuesta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PreguntaID = new SelectList(db.Pregunta, "ID", "Descripcion", respuesta.PreguntaID);
            ViewBag.Usuario_EncuestaID = new SelectList(db.Usuario_Encuesta, "ID", "ID", respuesta.Usuario_EncuestaID);
            return View(respuesta);
        }

        // GET: Respuestas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Respuesta respuesta = db.Respuesta.Find(id);
            if (respuesta == null)
            {
                return HttpNotFound();
            }
            ViewBag.PreguntaID = new SelectList(db.Pregunta, "ID", "Descripcion", respuesta.PreguntaID);
            ViewBag.Usuario_EncuestaID = new SelectList(db.Usuario_Encuesta, "ID", "ID", respuesta.Usuario_EncuestaID);
            return View(respuesta);
        }

        // POST: Respuestas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Usuario_EncuestaID,PreguntaID,Texto")] Respuesta respuesta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(respuesta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PreguntaID = new SelectList(db.Pregunta, "ID", "Descripcion", respuesta.PreguntaID);
            ViewBag.Usuario_EncuestaID = new SelectList(db.Usuario_Encuesta, "ID", "ID", respuesta.Usuario_EncuestaID);
            return View(respuesta);
        }

        // GET: Respuestas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Respuesta respuesta = db.Respuesta.Find(id);
            if (respuesta == null)
            {
                return HttpNotFound();
            }
            return View(respuesta);
        }

        // POST: Respuestas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Respuesta respuesta = db.Respuesta.Find(id);
            db.Respuesta.Remove(respuesta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: ResolverEncuesta
        public ActionResult ResolverEncuesta(int id_encuesta)
        {
            Session["encuesta_id"] = id_encuesta;
            var query = from pre in db.Pregunta
                        where pre.EncuestaID == id_encuesta
                        orderby pre.Orden 
                        select pre;
            List<Pregunta> preguntas = query.ToList();
            ViewBag.ListaPreguntas = preguntas;
            ViewBag.PreguntaID = new SelectList(db.Pregunta, "ID", "Descripcion");
            ViewBag.Usuario_EncuestaID = new SelectList(db.Usuario_Encuesta, "ID", "ID");
            return View();       
    }
        //POST: ResolverEncuesta
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResolverEncuesta(List<Respuesta> respuestas)
        {
            if (ModelState.IsValid)
            {
                int usuarioID = ((EncuestasINEI.Models.Usuario)Session["CurrentUser"]).ID;
                int encuestaID = (int)Session["encuesta_id"];

                //Crear usuario_encuesta
                Usuario_Encuesta objUsuarioEncuesta = new Usuario_Encuesta();
                objUsuarioEncuesta.UsuarioID = usuarioID;
                objUsuarioEncuesta.EncuestaID = encuestaID;
                db.Usuario_Encuesta.Add(objUsuarioEncuesta);
                db.SaveChanges();

                //Obtener el id de usuario_encuesta
                int usuario_encuestaID = objUsuarioEncuesta.ID;

                //Guardar las respuestas
                for(int a=0; a < respuestas.Count(); a++)
                {
                    Respuesta objRespuesta = new Respuesta();
                    objRespuesta.Usuario_EncuestaID = usuario_encuestaID;
                    objRespuesta.PreguntaID = respuestas[a].PreguntaID;
                    objRespuesta.Texto = respuestas[a].Texto;
                    db.Respuesta.Add(objRespuesta);
                    db.SaveChanges();
                }            
                return RedirectToAction("EncuestasParaUsuarios", "Encuestas", new { id_encuesta = encuestaID});
            }
            //ViewBag.PreguntaID = new SelectList(db.Pregunta, "ID", "Descripcion", respuesta.PreguntaID);
            //ViewBag.Usuario_EncuestaID = new SelectList(db.Usuario_Encuesta, "ID", "ID", respuesta.Usuario_EncuestaID);
            return View(respuestas);
        }

        // GET: DetallesEncuestaResuelta
        public ActionResult DetallesEncuestaResuelta(int encuestaID, int usuarioID )
        {
            int id_usuario = usuarioID;//((EncuestasINEI.Models.Usuario)Session["CurrentUser"]).ID;

            //Obtener la encuesta de la tabla usuario_encuesta
            var encuesta = from e in db.Usuario_Encuesta.Include(en => en.Encuesta).Include(u => u.Usuario)
                           where e.UsuarioID == id_usuario && e.EncuestaID == encuestaID
                           select e.ID;
            int us_en_id = encuesta.FirstOrDefault();

            //Obtener las respuestas de la encuesta
            var query = from res in db.Respuesta.Include(r => r.Pregunta).Include(r => r.Usuario_Encuesta)
                        where res.Usuario_EncuestaID == us_en_id
                        select res;

            List<Respuesta> respuestas = query.ToList();

            return View(respuestas);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/Create.cshtml
@model EncuestasINEI.Models.Encuesta

@{
    ViewBag.Title = "Crear";
}

<h2>Crear Encuesta</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Costo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Costo, new { htmlAttributes = new { @class = "form-control", @type = "number", @step="0.01", @min=0} })
                @Html.ValidationMessageFor(model => model.Costo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlcanceNacional, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AlcanceNacional)
                    @Html.ValidationMessageFor(model => model.AlcanceNacional, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/Delete.cshtml
@model EncuestasINEI.Models.Encuesta

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Está seguro de eliminar esta encuesta?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Costo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Costo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlcanceNacional)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlcanceNacional)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Volver", "Index")
        </div>
    }
</div>

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/Details.cshtml
@model EncuestasINEI.Models.Encuesta

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Costo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Costo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlcanceNacional)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlcanceNacional)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Volver", "Index")
</p>

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/Edit.cshtml
@model EncuestasINEI.Models.Encuesta

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Encuesta</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Fecha", Model.Fecha.ToString("yyyy-MM-dd"), new { @class = "form-control", @type = "date" })
                @*@Html.EditorFor(model => model.Fecha.ToString("yyyy-MM-dd"), new { htmlAttributes = new { @class = "form-control", @type = "date", @value = @Model.Fecha.ToString("yyyy-MM-dd") } })*@
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Costo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Costo, new { htmlAttributes = new { @class = "form-control", @type = "number", @step = "0.01", @min = 0 } })
                @Html.ValidationMessageFor(model => model.Costo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlcanceNacional, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AlcanceNacional)
                    @Html.ValidationMessageFor(model => model.AlcanceNacional, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/EncuestasActivas.cshtml
@model IEnumerable<EncuestasINEI.Models.Encuesta>

@{
    ViewBag.Title = "EncuestasActivas";
}

<h2>Encuestas Activas</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Costo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AlcanceNacional)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Costo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AlcanceNacional)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.ActionLink("Ver usuarios", "UsuariosPorEncuesta","Usuarios", new { id_encuesta=item.ID }, new { @title = "Ver usuarios asociados a esta encuesta"}) 
        </td>
    </tr>
}

</table>

@{ 
    Session["IDEncuesta"] = null;
}

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/EncuestasParaUsuarios.cshtml
@model IEnumerable<EncuestasINEI.Models.Encuesta>

@{
    ViewBag.Title = "EncuestasParaUsuarios";
}

<h2>Encuestas nuevas</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.ActionLink("Resolver encuesta", "ResolverEncuesta", "Respuestas", new { id_encuesta=item.ID }, null) 
        </td>
    </tr>
}

</table>

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/EncuestasPorCosto.cshtml
@model IEnumerable<EncuestasINEI.Models.Encuesta> 

@{
    ViewBag.Title = "EncuestasPorCosto";
}


<h2>Encuestas Por Costo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Costo1","Mínimo costo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Costo1", "", new { @class = "form-control valid", @data_val = "true", @data_val_required = "El monto es requerido",
                                                    @type = "number", @min = 0, @step = "0.01" })
            </div>
        </div>
        <div class="form-group">
           @Html.Label("Costo2", "Máximo costo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Costo2", "", new { @class = "form-control valid", @data_val = "true", @data_val_required = "El monto es requerido",
                                                    @type = "number", @min = 0, @step = "0.01"})
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Activo", "Activos", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBox("Activo")
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Inactivo", "Inactivos", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBox("Inactivo")
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buscar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (Session["Encuestas"] != null)
{
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fecha)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Costo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AlcanceNacional)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th></th>
            </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Costo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AlcanceNacional)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
            </tr>
        }
        </table>
}

else if (ViewBag.Resultado != null)
{
    <font color="red">@ViewBag.Resultado</font>
}
 
@{ 
    Session["Encuestas"] = null;
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/EncuestasRealizadas.cshtml
@model IEnumerable<EncuestasINEI.Models.Encuesta>

@{
    ViewBag.Title = "EncuestasRealizadas";
}

<h2>Mis encuestas</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.ActionLink("Detalles", "DetallesEncuestaResuelta","Respuestas", 
           new { encuestaID = item.ID, usuarioID = ((EncuestasINEI.Models.Usuario)Session["CurrentUser"]).ID }, null) 
        </td>
    </tr>
}

</table>
@*<p>
    @Html.ActionLink("Volver", "EncuestasParaUsuarios")
</p>*@

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/Index.cshtml
@model IEnumerable<EncuestasINEI.Models.Encuesta>

@{
    ViewBag.Title = "Index";
}

<h2>Mis encuestas</h2>

<p>
    @Html.ActionLink("Crear nuevo", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Costo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AlcanceNacional)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Costo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AlcanceNacional)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.ID }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.ID }) |
            @Html.ActionLink("Preguntas", "Index", "Preguntas", new { id_encuesta = item.ID }, null)
        </td>
    </tr>
}

</table>

EncuestasINEI_PU/EncuestasINEI/Views/Encuestas/TopEncuestas.cshtml
@model IEnumerable<EncuestasINEI.Models.Encuesta>

@{
    ViewBag.Title = "Top Encuestas";
}

<h2>TOP Encuestas</h2>

<div>
    <img src="@Url.Action("Reporte5")" alt="ChartBar" />
</div>